---

  - name: Generate the zookeeper url
    set_fact: mesos_zookeeper_masters="zk://{% for i in groups['zookeeper'] %}{{ hostvars[i]['ansible_eth0']['ipv4']['address'] }}:2181{% if not loop.last %},{% endif %}{%endfor %}/mesos"
    tags: [reconfigure,bootstrap]
  
  - name: Compute the quorum 
    set_fact: mesos_quorum={{ (( groups['zookeeper'] | count)/2) | round | int }}
    tags: [reconfigure,bootstrap]