---

- name: Add the mesos repository to yum.
  include: add-mesos-repo.yml
  tags: bootstrap

- name: Add the logger directory
  file: path=/var/log/zookeeper state=directory mode=0755
  tags: bootstrap


- name: Install the zookeeper
  yum: name=mesosphere-zookeeper-{{ zookeeper_version }} update_cache=yes
  tags: deploy
  notify:
    - Start zookeeper

- name: Systemd script.
  template: src=zookeeper.service.j2 dest=/usr/lib/systemd/system/zookeeper.service
  tags: reconfigure
  notify:
    - Reload systemd
    - Restart zookeeper

- name: Write myid file.
  template: src=myid.j2 dest=/var/lib/zookeeper/myid owner=root group=root
  tags: reconfigure
  notify:
    - Restart zookeeper

- name: Configure zookeeper
  template: src=zoo.cfg.j2 dest=/etc/zookeeper/conf/zoo.cfg owner=root group=root
  tags: reconfigure
  notify:
    - Restart zookeeper


